### ISSUE TITLE
关于代理转发路径问题

### ISSUE THREAD

**Issue by chinazman** [TeaWeb/build#11]
比如配置代理转发的前缀匹配为/demo，我请求的路径是/demo/aaa。我希望发给后端服务器的请求地址是/aaa,目前请求URI配置为${requestURI}实际上是全路径/demo/aaa,不是我想要的，看是否增加一个变量来表示，我觉得这个需求应该是非常有必要，目前ngnix那边配置location，传到后端的话，就是会排除前缀的。

**Comment by chinazman** [comment]
或者这边有没有其他解决方式？我通过配置rewrite貌似和后端服务器是互斥的，没有将rewrite后的请求发给后端服务器，

**Comment by iwind** [comment]
试试下面方法：
1、设置前缀匹配路径规则/demo
2、在此规则下添加重写规则rewrite：/demo/(.+)   =>  /${1}

**Comment by iwind** [comment]
如果是把后端服务器放在了路径规则里的，可以：
1、设置正则匹配的路径规则^/demo/(?P<path>.+)
2、在后端服务器中设置请求URI为：/${path}?${args}

**Comment by iwind** [comment]
如果没有回应的话，先视为已解决
