### ISSUE TITLE
访问日志 添加 响应Body数据

### ISSUE THREAD

**Issue by luomoxu** [TeaWeb/build#14]
打算尝试用于开发环境管理，能记录响应Body数据的话 可以用来定位一些具体的接口问题

**Comment by iwind** [comment]
在实时日志中，选中”抓取“按钮变蓝色，即可实时抓取请求和响应内容

**Comment by luomoxu** [comment]
很多时候出问题的的请求的情况都是不确认的 主要是想快速的回溯一个具体的请求的返回结果

**Comment by zhfish** [comment]
同需求，需要保存request的body

**Comment by iwind** [comment]
v0.1.4版本发布了，这个版本支持设置访问日志里记录请求Body和响应Body，而且如果是application/json格式的还可以高亮，可以在这里 http://teaos.cn/download 下载。

**Comment by luomoxu** [comment]
十分感谢
