### ISSUE TITLE
响应数据Body非json格式时乱码

### ISSUE THREAD

**Issue by luomoxu** [TeaWeb/build#16]
响应数据Body非json格式时乱码

**Comment by iwind** [comment]
有截图可以看吗？

**Comment by luomoxu** [comment]
![image](https://user-images.githubusercontent.com/1317574/58144774-5da1fa80-7c82-11e9-8e4c-02593da0df04.png)

**Comment by iwind** [comment]
知道了，这是gzip压缩后的内容，新版本会支持。

**Comment by iwind** [comment]
新版本v0.1.5已经发布并支持了压缩内容的预览。

**Comment by luomoxu** [comment]
感谢~
