### ISSUE TITLE
dashboard 异常

### ISSUE THREAD

**Issue by carter911** [TeaWeb/build#19]
你安装的TeaWeb版本：0.1.4.1

你的操作系统：ubuntu16

你的问题简介：dashboard 异常

问题详细描述：  /Users/liuxiangchao/Documents/Projects/pp/apps/TeaWebGit/build/src/github.com/TeaWeb/code/teaweb/actions/default/agents/board/index.go:116
[2019/05/29 11:19:06]  Error: context deadline exceeded

**Comment by iwind** [comment]
MongoDB连接正常吗

**Comment by carter911** [comment]
db连接正常 首次开启都正常 运行一会就报这个错误

**Comment by iwind** [comment]
看看新版本v0.1.5会不会还有这个问题，v0.1.5修复了运行一段时间网络连接数过多的问题。

**Comment by iwind** [comment]
新版本应该已经解决，先关闭
