### ISSUE TITLE
centos7下HTTPS修改界面空白

### ISSUE THREAD

**Issue by shenshunan** [TeaWeb/build#21]
你安装的TeaWeb版本：v0.1.5

你的操作系统：CentOS7

你的问题简介：进入代理-默认的静态网站-设置-HTTPS，点击修改，页面空白

问题详细描述：以为是linux权限问题，不管用root还是用普通账户，目录也改了chown，都是一样的结果。

**Comment by iwind** [comment]
已修复，并发了新版本v0.1.5.1，非常感谢

**Comment by iwind** [comment]
新版本已解决，先关闭
