### ISSUE TITLE
本地服务检测

### ISSUE THREAD

**Issue by phonehold** [TeaWeb/build#3]
本地服务检测，检测不到。不管是nginx  redis 等

**Comment by phonehold** [comment]
要重启teaweb才能生效。。这个和APP 插件有关系的吧

**Comment by TeaWeb** [comment]
是的，是App插件的Bug

**Comment by inuxor** [comment]
好多服务识别不到
mysql，rabbitMQ，apache都没有
在我的PC上只能识别下面这些
![default](https://user-images.githubusercontent.com/1345457/49978420-798fca80-ff85-11e8-8ffe-b462c491aa9f.png)

在我们的开发服务器上更惨，只有redis和mongodb

**Comment by TeaWeb** [comment]
目前只提供了示例，继续努力完善中

**Comment by iwind** [comment]
未来使用新的机制实现本地服务检测。
