### ISSUE TITLE
agent的监控项dns目前只支持A类地址范围，是否考虑支持AAAA的返回

### ISSUE THREAD

**Issue by bobzhangfw** [TeaWeb/build#33]
你安装的TeaWeb版本：0.1.6.1

你的操作系统：win2008

你的问题简介：agent监控项支持DNS A类返回，不支持AAAA类

问题详细描述：由于IPV6使用扩展，需要支持AAAA类地址的返回。

**Comment by bobzhangfw** [comment]
测试发现使用A，可以返回IPV6的地址。和V4的地址混在一起返回来。

**Comment by iwind** [comment]
下个版本0.1.7会新增AAAA选项，但是实现是和IPv4一样的。

**Comment by iwind** [comment]
在v0.1.7中，新增AAAA选项，但是实现是和IPv4一样的。
