### ISSUE TITLE
监控项建议

### ISSUE THREAD

**Issue by xieyuhua** [TeaWeb/build#34]
监控项里面的刷新间隔，以后是否考虑Cron 这种格式，

**Comment by iwind** [comment]
这倒是有意思的想法，可以具体举几个应用的实例吗？

**Comment by xieyuhua** [comment]
其实跟监控没关系，我只是想如果支持Cron 这种格式，就可以做一些定时任务了，根据返回结果判断任务执行是否正常执行，然后通知

**Comment by xieyuhua** [comment]
哈哈，抱歉，我没有注意后面有个定时任务。

**Comment by iwind** [comment]
是的，可以自定义定时任务，精确到秒。

**Comment by WUYANGHAO** [comment]
希望加上监控磁盘读写性能

**Comment by iwind** [comment]
> 希望加上监控磁盘读写性能

合并到 https://github.com/TeaWeb/build/issues/38
