### ISSUE TITLE
agent手工安装优化

### ISSUE THREAD

**Issue by maxtorgithub** [TeaWeb/build#36]
建议增加手工安装agent的自动发现机制，减少agent端配置文件的修改。agent通过ip首次上线后由管理员确认后就可以加入集群，然后再生成认证密钥。

**Comment by iwind** [comment]
可能会实现的方式是在TeaWeb给每个分组生成一个Key，然后Agent利用这个Key即可自动注册，类似于：
~~~bash
bin/agent -key=0bd670de91d8fb906415c5941f577eb2
~~~
或
~~~bash
bin/agent start -key=0bd670de91d8fb906415c5941f577eb2
~~~

**Comment by iwind** [comment]
在0.1.7中会加入：http://teaos.cn/doc/agents/InstallGroupKey.md
