### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by phonehold** [TeaWeb/build#4]
能否定位非开发环境的场景，考虑性能方向。这样就可以代替haproxy 了。线上跑跑。
如果能有个WAF ，就prefect了

**Comment by TeaWeb** [comment]
性能和稳定性是TeaWeb未来能否成功的两大核心基础，以后每个版本都会在这两方面有所提升。你说的WAF是Web application firewall吗？可以具体说一下，或者加入我们的QQ群：199435611跟大家一起分享你的经验和建议。

**Comment by wi1dcard** [comment]
搭车问：有 Telegram 群吗？

@TeaWeb

**Comment by iwind** [comment]
> 搭车问：有 Telegram 群吗？
> 
> @TeaWeb

还没有，那个在国内无法登录。

**Comment by wi1dcard** [comment]
好吧，还是有部分人在墙外，并且不使用墙内通讯工具的。

**Comment by iwind** [comment]
v0.1.3已经实现了WAF功能，文档：http://teaos.cn/doc/waf/Index.md 下载地址：http://teaos.cn/download/beta

**Comment by iwind** [comment]
没有进一步的回复，暂时先关闭。
