### ISSUE TITLE
服务器和代理客户机时间不同步

### ISSUE THREAD

**Issue by bobzhangfw** [TeaWeb/build#49]
你安装的TeaWeb版本：0.1.6.1

你的操作系统：windows 2008R2

你的问题简介：服务器时间不对，客户端时间正确。逻辑好像不太对

问题详细描述：客户端提交的数据存储日志时按照服务端时间存储，貌似应该记录客户机时间。

**Comment by iwind** [comment]
在v0.1.8中修复
