### ISSUE TITLE
v0.0.8 登录有问题

### ISSUE THREAD

**Issue by phonehold** [TeaWeb/build#5]
如果输入错的用户名和密码，会提示不正确。
如果输入对的。点登录后一直让重新输入
测试环境centos 7
用的二进制的版本
[root@builder-centos7 teaweb-v0.0.8]# cat logs/teaweb.log 
2019/02/14 17:24:15 kill previous process 9965
2019/02/14 17:24:15 [plugin]load plugins
2019/02/14 17:24:15 [plugin][loader]load plugin 'agent.tea'
2019/02/14 17:24:15 load sessions from files /root/teaweb-v0.0.8/tmp
2019/02/14 17:24:15 start http server on 0.0.0.0:7777
2019/02/14 17:25:21 server selection timeout
                /Users/liuxiangchao/Documents/Projects/pp/apps/TeaWebGit/build/src/github.com/TeaWeb/code/teaweb/actions/default/api/agent/push.go:142
2019/02/14 17:25:21 server selection timeout
                /Users/liuxiangchao/Documents/Projects/pp/apps/TeaWebGit/build/src/github.com/TeaWeb/code/teaweb/actions/default/api/agent/push.go:142
2019/02/14 17:25:21 server selection timeout
                /Users/liuxiangchao/Documents/Projects/pp/apps/TeaWebGit/build/src/github.com/TeaWeb/code/teaweb/actions/default/api/agent/push.go:142
2019/02/14 17:25:24 server selection timeout

访问日志也没有看到有。只有这个。

**Comment by TeaWeb** [comment]
server selection timeout是mongoDB连接错误，请在设置中设置MongoDB连接即可。

**Comment by TeaWeb** [comment]
相关文档可以看这里：http://plus.teaos.cn/doc/main/Install.md

**Comment by TeaWeb** [comment]
还有，登录失败可能是因为session文件无法写 tmp/ 目录导致，试着修改TeaWeb下的tmp目录权限试试。

**Comment by iwind** [comment]
Hi，现在问题解决了吗？如果没有解决，可以加QQ群： 199435611

**Comment by phonehold** [comment]
@iwind 抱歉，邮件有问题，没收到，回头空了我测试一下。

**Comment by phonehold** [comment]
@iwind 加了群了，没同意我进去。 还是依旧有问题

**Comment by iwind** [comment]
已经同意入群了，是 贝奇小天狼星 这个吧

**Comment by iwind** [comment]
经验证，是Chrome偶发Bug，清除Cookie记录后重新登录即可。
