### ISSUE TITLE
【特性需求】建议隧道客户端支持服务安装

### ISSUE THREAD

**Issue by jack3rpopov** [TeaWeb/build#52]
你安装的TeaWeb版本：0.1.7.2

你的操作系统：windows 2012 datacenter r2

你的问题简介：建议 > 隧道客户端支持服务安装

问题详细描述：忘下个版本也能加上服务安装。

**Comment by iwind** [comment]
在tunnel客户端v1.0.3中加入，已经在官网 http://teaos.cn/download#tunnel 可以下载。
