### ISSUE TITLE
建议增加 openwaf 功能

### ISSUE THREAD

**Issue by alex1528** [TeaWeb/build#6]
可以参考 Jenusec 项目中的 waf 规则

**Comment by iwind** [comment]
在网上没搜到Jenusec这个项目，能否给个地址学习一下？

**Comment by jumping** [comment]
https://github.com/Janusec/janusec

**Comment by iwind** [comment]
谢谢，已关注

**Comment by phonehold** [comment]
@iwind 本身项目部署是在waf在前，如果用了teaweb，则只能再多一层，放在teaweb后面。比较麻烦。如果没有waf，则安全性又是个问题

**Comment by alex1528** [comment]
acl 功能最好也要有.

**Comment by iwind** [comment]
v0.1.3已经实现了WAF功能，文档：http://teaos.cn/doc/waf/Index.md   下载地址：http://teaos.cn/download/beta

**Comment by iwind** [comment]
无更多回复，暂时关闭。
