### ISSUE TITLE
teaweb自身会报500错误

### ISSUE THREAD

**Issue by 9527code** [TeaWeb/build#61]
你安装的TeaWeb版本：v0.1.8

你的操作系统：centos7

你的问题简介：
http代理自身会报500错误，具体错误是什么也不知道
响应的body是:Internal Server Error，我测试过不是后端报的，就是teaweb报的

问题详细描述：
后来查了下日志accesslog.7.0.log定位到错误是这样的

"errors": ["Get http://www.xxx.com/xxx/xxx/.html: context canceled"],
    "hasErrors": true,
    "extend": {

**Comment by 9527code** [comment]
对了，缓存是用的redis，不知道是不是这个原因

**Comment by 9527code** [comment]
还有这个代理统计数据是强制开启的？关闭了还是在记录日志

**Comment by 9527code** [comment]
线上环境使用，问题无法重放，自己打开报500的页面是正常的，就是日志里有不少这样的错误

**Comment by iwind** [comment]
这个是请求超时的意思，可以在系统日志里查看详细的信息。

**Comment by 9527code** [comment]
不是超时的,超时应该是有其他的提示.主要是没法重放进行debug，线上环境又一堆这样的错误，烦

**Comment by iwind** [comment]
> 不是超时的,超时应该是有其他的提示.主要是没法重放进行debug，线上环境又一堆这样的错误，烦

在TeaWeb界面左侧菜单“系统日志”里会记录详细的代码文件和行数，所以需要在那里看一下具体的代码。

还有，TeaWeb会更加忠实地记录每一个微不足道的错误提示，虽然可能有些人觉得有点烦。

**Comment by 9527code** [comment]
不是烦这个报错提示，我这很多这种错误，可以想象多少用户的体验，网站老是500报错。
我是烦定位不到错误所在

**Comment by 9527code** [comment]
`[2019/10/30 20:32:23]  context canceled
        src/github.com/TeaWeb/code/teaproxy/request_backend.go:233`
日志里有这样的，但是这种日志太少了，和访问监控里面的数目差太多了，差了几百倍
