### ISSUE TITLE
哪个版本支持企业微信？

### ISSUE THREAD

**Issue by hazhaonc** [TeaWeb/build#9]
教程中介绍在‘媒介’添加 企业微信，在v0.0.10.3里还没有看到

**Comment by iwind** [comment]
下个版本v0.1，正在测试中，近期发布。

**Comment by iwind** [comment]
新版本发布了哦，支持企业微信和钉钉群机器人，这里下载：http://teaos.cn/download  这里看版本说明：https://github.com/TeaWeb/build/releases/tag/v0.1

**Comment by iwind** [comment]
问题应该已得到解决，所以先关闭
